package com.andreafilice.lavorami;

public enum DataKeys {
    /// This Enumerator is for Keep the KEYS all saved in a single file
    /// and avoid mismatches with Strings.
    /// @PARAMETER no Parameters in this Enumerator.
    /// @FALLBACK Fallback Rule: no Fallback rules.

    KEY_DEFAULT_FILTER,
    KEY_DEFAULT_THEME,
    KEY_NOTIFICATION_SWITCH,
    KEY_NOTIFICATION_STARTWORKS,
    KEY_NOTIFICATION_ENDWORKS,
    KEY_NOTIFICATION_STRIKES,
    KEY_NOTIFICATION_PUSH,
    KEY_HOURS_NOTIFICATIONS,
    KEY_MINUTES_NOTIFICATIONS,
    KEY_FAVORITE_LINES,
    KEY_SHOW_ERROR_MESSAGES,
    KEY_SHOW_BANNERS,
    KEY_REQUIRE_BIOMETRICS,
    KEY_HAPTIC_FEEDBACKS,
    KEY_SHOW_TRANSLATE_BUTTON,
    KEY_SHOW_RECENT_LINES,
    KEY_END_SETUP,
    KEY_DEFAULT_LANGUAGE,
    KEY_DOWNLOAD_POLICIES,
    KEY_ARRAY_RECENT_LINES,
    KEY_ARRAY_YOUR_LINES,
    KEY_HINT_SAVED_LINES_CLOSED,
    KEY_SAVE_DB_FAVORITES,
    KEY_SAVE_DB_YOUR_LINES,
    KEY_OPEN_LINK_TYPE,
    KET_OPEN_ALL_LINES
}
